version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: msisdn-info-webserver
      working_dir: /application/public
      volumes:
          - .:/application
          - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: .docker
      container_name: msisdn-info-php-fpm
      working_dir: /application
      volumes:
        - .:/application
